= Полезности
:toc:

В этом доке я собрал избранные материалы по математике, программированию и софт-скилам (да-да).
У школы нет возможности дать достаточные знания для комфортной учёбы на математических или программистских специальностях из-за консервативных учебных планов и недостатка учебных часов.
Но это ещё пол беды.
Большинство студентов, успешно сдавших ЕГЭ и прочее очень быстро отваливаются буквально с первых курсов не потому, что не в состоянии справиться с материалом (хотя это тоже большая проблема), а потому что не умеют планировать свое время, поддерживать своё психологическое и эмоциональное состояние в пригодном для длительной тяжелой учебы виде.
Такие мета-навыки, к которым относится и общее умение учиться, называются "мягкими" навыками.
Они не изучаются в школе, но являются жизненно необходимыми.

== Где учиться

https://habr.com/ru/company/JetBrains-education/blog/[Паблик JetBrains Education] на хабре публикует информацию о своих образовательных программах, а так же часто -- интервью со своими студентами.
Оттуда можно узнать: где и как можно учиться, что важно знать и понимать и какие бывают сложности.

.Онлайн
- https://stepik.org/ содержит огромное количество бесплатных курсов по математике и программированию.
Развивается компанией JetBrains.
Самыми качественными курсами там являются курсы от https://compscicenter.ru/[Computer Science Center] -- https://stepik.org/org/compscicenter.
Других хороших там тоже много.
- https://www.coursera.org/ самый большой хостинг онлайн образования.
Много курсов как от российских вузов типа физтеха и вышки, так и от западных.
Бесплатные курсы там тоже встречаются
- Таких платформ ещё много:
. https://www.udacity.com/
. https://www.edx.org/
. https://www.jetbrains.com/ru-ru/academy/
. ...
- Ютуб ЦС центра, клуба и рядом:
. https://www.youtube.com/c/CompscicenterRu
. https://www.youtube.com/c/ComputerScienceClub
. https://www.youtube.com/c/VitalyBragilevsky
- Ютубы айтишных конференций, там есть и популярные доклады, чтобы понимать что в каком состоянии:
.https://www.youtube.com/c/Heisenbugconf
. https://www.youtube.com/c/CUserGroupRussia
. https://www.youtube.com/c/HolyJS
. https://www.youtube.com/c/JSConfEU
. https://www.youtube.com/c/JUGru
. https://www.youtube.com/c/MobiusConf
. https://www.youtube.com/c/TechTrainFest
- Ютуб айтишных подкастов: https://www.youtube.com/c/PodlodkaShow, https://www.youtube.com/c/ITBEARD
- Ютуб популярной науки:
. https://www.youtube.com/c/3blue1brown
. https://www.youtube.com/user/Computerphile
. https://www.youtube.com/channel/UCQj_dwbIydi588xrfjWSL5g
. https://www.youtube.com/c/%D0%9A%D0%BE%D0%BC%D0%BF%D1%8C%D1%8E%D1%82%D0%B5%D1%80%D0%BD%D1%8B%D0%B5%D0%BD%D0%B0%D1%83%D0%BA%D0%B8
. https://www.youtube.com/c/HexletOrg
- Ютуб университетов:
. https://www.youtube.com/channel/UCyE7AvYBGTt0uPV_WTWRvTg
. https://www.youtube.com/c/AndreySozykinCS
. https://www.youtube.com/channel/UC6Jli3lX-oOFYh4wNF9rXFA
. https://www.youtube.com/channel/UCWhjTcsW0OgSuJBoVg7Pb_w
. https://www.youtube.com/channel/UCfAkcdNAMq65AA5KVPiEyVg
. https://www.youtube.com/c/%D0%9B%D0%B5%D0%BA%D1%82%D0%BE%D1%80%D0%B8%D0%B9%D0%A4%D0%9F%D0%9C%D0%98
. https://www.youtube.com/c/%D0%A4%D0%9A%D0%9D%D0%92%D0%A8%D0%AD
- Ютуб лабораторий: https://www.youtube.com/c/JetBrainsResearchRus
- Ютуб моей магистратуры: https://www.youtube.com/channel/UCXlQre5nhVnfMLxNtlK7BPQ

.Корпоративные курсы
- Яндекс Лицей -- https://yandexlyceum.ru/
- Лаборатория JetBrain Research делает школу андроид разработки для старшекласников -- https://research.jetbrains.org/ru-ru/groups/robolab/schools/kotlin-for-android-online-21-22/

.Летние и зимние школы
- ЛКШ (Летняя Компьютерная Школа) -- https://lksh.ru/
- Ещё есть школы по математике, физике и проч.
Могу узнать, если интересно, пишите в личку.

== Математика

TODO

== Программирование

TODO

== Soft skills

TODO
